import React, { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

export default function HeaderComp() {
  const [isClicked, setisClicked] = useState(false);
  const Router = useRouter();

  return (
    <>
      <Head>
        <title>Storlly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed w-full m-auto left-0 top-0 z-[1000]">
        <header className="px-3 py-3 w-full lg:w-11/12 m-auto flex justify-between items-center bg-white">
          <div className="w-4/12">
            <Link href="/">
              <img src="./logo.svg" alt="" />
            </Link>
          </div>
          <div className="w-4/12 hidden lg:block">
            <ul className="flex gap-10 text-sm mt-1">
              <li className="cursor-pointer">FEATURES</li>
              <li className="cursor-pointer">BLOG</li>
              <li className="cursor-pointer">SUPPORT</li>
              <li className="cursor-pointer">FAQ</li>
            </ul>
          </div>
          <div className="hidden lg:block w-4/12 ">
            <div className="flex justify-end gap-10 items-center">
              <Link href="/login">
                <span className="cursor-pointer">Login</span>
              </Link>
              <button
                className="px-6 py-[0.6rem] bg-storllyblack text-white rounded-md"
                onClick={() => Router.push("/createaccount")}
              >
                Get Started
              </button>
            </div>
          </div>
          <div
            className=" lg:hidden w-8 h-8 flex items-center flex-col justify-center gap-[0.18rem]"
            onClick={() => setisClicked(!isClicked)}
          >
            <div className="h-[0.18rem] w-full bg-storllyblack"></div>
            <div className="h-[0.16rem] w-full bg-storllyblack"></div>
            <div className="h-[0.16rem] w-full bg-storllyblack"></div>
          </div>
        </header>
        <div
          className={`lg:hidden absolute  h-[100vh] backdrop-blur-sm bg-slate-800 w-8/12 top-14 ${
            isClicked ? "right-0" : "right-[-200rem]"
          }`}
        ></div>
      </div>
    </>
  );
}
