import React, { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

export default function UserHeaderComp() {
  const [isClicked, setisClicked] = useState(false);
  const Router = useRouter();

  const tabs = [
    { title: "Profile", path: "./profile" },
    { title: "Add Product", path: "./profile" },
    { title: "Messages", path: "./profile" },
    { title: "Orders", path: "./orders" },
    { title: "Manage Store", path: "./store-management" },
    { title: "Settings", path: "./orders" },
    { title: "Logout", path: "" },
  ];

  const Tab = ({ title, path }: any) => {
    return (
      <div className="bg-slate-100 hover:bg-slate-200 transition-all ease-in delay-100 py-4 px-3 mb-3 flex justify-between items-center cursor-pointer">
        <h4 className="text-sm text-slate-900 font-light hover:text-storllyblack  transition-all ease-out delay-300">
          {title}
        </h4>
        <svg
          width="8"
          height="14"
          viewBox="0 0 8 14"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M0.167835 0.158175C0.220903 0.108036 0.283944 0.0682557 0.35335 0.0411135C0.422755 0.0139713 0.49716 0 0.572304 0C0.647447 0 0.721852 0.0139713 0.791258 0.0411135C0.860663 0.0682557 0.923705 0.108036 0.976772 0.158175L7.83216 6.61896C7.88537 6.66897 7.92758 6.72838 7.95638 6.79379C7.98518 6.8592 8 6.92932 8 7.00014C8 7.07096 7.98518 7.14108 7.95638 7.20649C7.92758 7.2719 7.88537 7.33131 7.83216 7.38133L0.976772 13.8421C0.8695 13.9432 0.724009 14 0.572304 14C0.420599 14 0.275107 13.9432 0.167835 13.8421C0.0605638 13.741 0.000299105 13.6039 0.000299105 13.4609C0.000299105 13.3179 0.0605638 13.1808 0.167835 13.0797L6.6199 7.00014L0.167835 0.920547C0.114634 0.870534 0.0724241 0.811122 0.0436241 0.745711C0.0148241 0.680301 0 0.610179 0 0.539361C0 0.468543 0.0148241 0.398421 0.0436241 0.33301C0.0724241 0.2676 0.114634 0.208187 0.167835 0.158175Z"
            fill="#16191B"
          />
        </svg>
      </div>
    );
  };

  const tablist = tabs.map((tab, index) => (
    <div key={index}>
      <Tab title={tab.title} />
    </div>
  ));

  return (
    <>
      <Head>
        <title>Storlly | Usertag</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed w-full m-auto left-0 top-0 z-[1000]">
        <header className="px-3 border-b border-black py-4 w-full lg:w-11/12 m-auto flex justify-between items-center bg-white">
          <div className="w-4/12">
            <Link href="/usertag">
              <img src="/logo.svg" alt="" />
            </Link>
          </div>

          <div className="hidden lg:block w-4/12 ">
            <div className="flex justify-end gap-10 items-center">
              <div className=" cursor-pointer">
                <svg
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M19.5 8C21.43 8 23 6.43 23 4.5C23 2.57 21.43 1 19.5 1C17.57 1 16 2.57 16 4.5C16 6.43 17.57 8 19.5 8ZM21 16V9.79C20.5 9.93 20 10 19.5 10H19V16C19 17.66 17.66 19 16 19H8C6.34 19 5 17.66 5 16V8C5 6.34 6.34 5 8 5H14V4.5C14 4 14.07 3.5 14.21 3H8C5.24 3 3 5.24 3 8V16C3 18.76 5.24 21 8 21H16C18.76 21 21 18.76 21 16Z"
                    fill="black"
                  />
                </svg>
              </div>
              <div className=" cursor-pointer">
                <svg
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M20 2H4C2.9 2 2 2.9 2 4V16C2 17.1 2.9 18 4 18H18L22 22V4C22 2.9 21.1 2 20 2ZM20 17.2L18.8 16H4V4H20V17.2Z"
                    fill="black"
                  />
                </svg>
              </div>
              <div className=" cursor-pointer">
                <svg
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M11 19V13H5V11H11V5H13V11H19V13H13V19H11Z"
                    fill="black"
                  />
                </svg>
              </div>
              <div
                className="cursor-pointer"
                onClick={() => setisClicked(!isClicked)}
              >
                <svg
                  width="18"
                  height="12"
                  viewBox="0 0 18 12"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M0.500003 11.0012V11C0.500003 10.8429 0.547773 10.7343 0.641557 10.6406C0.735279 10.5468 0.843084 10.4996 0.998824 10.5H1H17C17.1572 10.5 17.2657 10.5478 17.3594 10.6416C17.4532 10.7353 17.5004 10.8431 17.5 10.9988V11C17.5 11.1572 17.4522 11.2657 17.3584 11.3594C17.2647 11.4532 17.1569 11.5004 17.0012 11.5H17H1C0.842852 11.5 0.73434 11.4522 0.640557 11.3584C0.546835 11.2647 0.499635 11.1569 0.500003 11.0012ZM0.500003 6.00118V6C0.500003 5.84285 0.547773 5.73434 0.641557 5.64056C0.735278 5.54683 0.843083 5.49963 0.998824 5.5H1H17C17.1572 5.5 17.2657 5.54777 17.3594 5.64156C17.4532 5.73528 17.5004 5.84308 17.5 5.99882V6C17.5 6.15715 17.4522 6.26567 17.3584 6.35945C17.2647 6.45317 17.1569 6.50037 17.0012 6.5H17H1C0.842852 6.5 0.73434 6.45223 0.640557 6.35845C0.546835 6.26473 0.499635 6.15692 0.500003 6.00118ZM0.500002 1.00118H0.500003V1C0.500003 0.842852 0.547773 0.734341 0.641557 0.640557C0.735279 0.546835 0.843084 0.499635 0.998824 0.500002V0.500003H1H17C17.1572 0.500003 17.2657 0.547773 17.3594 0.641557C17.4532 0.735279 17.5004 0.843084 17.5 0.998824V1C17.5 1.15715 17.4522 1.26567 17.3584 1.35945C17.2647 1.45317 17.1569 1.50037 17.0012 1.5H17H1C0.842852 1.5 0.73434 1.45223 0.640557 1.35845C0.546835 1.26473 0.499635 1.15692 0.500002 1.00118Z"
                    fill="black"
                    stroke="black"
                  />
                </svg>
              </div>
              <div className="w-8 h-8 bg-slate-300 rounded-full"></div>
            </div>
          </div>
          <div
            className=" lg:hidden w-8 h-8 flex items-center flex-col justify-center gap-[0.18rem]"
            onClick={() => setisClicked(!isClicked)}
          >
            <div className="h-[0.18rem] w-full bg-storllyblack"></div>
            <div className="h-[0.16rem] w-full bg-storllyblack"></div>
            <div className="h-[0.16rem] w-full bg-storllyblack"></div>
          </div>
        </header>
        <div
          className={` lg:hidden absolute mt-2  h-[100vh] backdrop-blur-xs bg-white py-2  w-6/12 lg:w-2/12 lg:right-16 top-14 ${
            isClicked ? "right-0" : "right-[-200rem]"
          }`}
        >
          {tablist}
          <div className="mt-20 border-t border-slate-200">
            <ul className="flex gap-4 justify-center mt-10 text-xs text-slate-500">
              <li className="cursor-pointer">Terms</li>
              <li>|</li>
              <li className="cursor-pointer">Support</li>
            </ul>
          </div>
        </div>

        <div
          className={` hidden lg:block absolute py-4 mt-2  h-[100vh] backdrop-blur-xs bg-white  w-8/12 lg:w-3/12 xl:w-2/12 top-14 ${
            isClicked ? "lg:right-11 xl:right-[3.6rem]" : "right-[-200rem]"
          }`}
        >
          {tablist}
          <div className="mt-20 border-t border-slate-200">
            <ul className="flex gap-4 justify-center mt-10 text-xs text-slate-500">
              <li className="cursor-pointer">Terms</li>
              <li>|</li>
              <li className="cursor-pointer">Support</li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}
